services:
  - type: web
    name: my-php-app
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t /public"
    envVars:
      - key: PORT
        value: "10000"
